/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tetris2024;

import java.io.File;
import java.util.*;
import javax.sound.sampled.*;

/**
 *
 * @author alu10654799
 */
public class Tetris2024 extends javax.swing.JFrame {

    /**
     * Creates new form Tetris2024
     */
    public Tetris2024() {
        initComponents();
        setLocationRelativeTo(null);
        board.setScoreInterface(scoreBoard);
        ConfigDialog configDialog = new ConfigDialog(this, true);
        configDialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoreBoard = new com.mycompany.tetris2024.ScoreBoard();
        jToolBar2 = new javax.swing.JToolBar();
        jButtonPlay = new javax.swing.JButton();
        jButtonPause = new javax.swing.JButton();
        board = new com.mycompany.tetris2024.Board();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scoreBoard.setPreferredSize(new java.awt.Dimension(250, 33));
        getContentPane().add(scoreBoard, java.awt.BorderLayout.PAGE_END);

        jToolBar2.setRollover(true);

        jButtonPlay.setText("Play");
        jButtonPlay.setFocusable(false);
        jButtonPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPlay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonPlay);

        jButtonPause.setText("Pause");
        jButtonPause.setFocusable(false);
        jButtonPause.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPause.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPauseActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonPause);

        getContentPane().add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        board.setPreferredSize(new java.awt.Dimension(250, 594));
        getContentPane().add(board, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        board.initGame();
        playRandomAudio();
    }//GEN-LAST:event_jButtonPlayActionPerformed

    private void jButtonPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPauseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tetris2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tetris2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tetris2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tetris2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tetris2024().setVisible(true);
            }
        });
    }
    
    public static void playAudio(String ruta) {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(
                    new File(ruta).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.addLineListener(new LineListener() {
                @Override
                public void update(LineEvent event) {
                    if (event.getType() == LineEvent.Type.STOP) {
                        clip.setFramePosition(0);
                        clip.start();
                    }
                }
            });
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public static void playRandomAudio() {
        String[] rutas = {
            "src/main/resources/audio/tetris-techno.wav",
            "src/main/resources/audio/troll.wav",
            "src/main/resources/audio/argentino.wav"
        };
        Random random = new Random();
        int index = random.nextInt(rutas.length);
        playAudio(rutas[index]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.tetris2024.Board board;
    private javax.swing.JButton jButtonPause;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JToolBar jToolBar2;
    private com.mycompany.tetris2024.ScoreBoard scoreBoard;
    // End of variables declaration//GEN-END:variables
}
