/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1;

import static com.mycompany.mavenproject1.MineButton.BUTTOM_SIZE;
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author alu13114532
 */
public class Board extends javax.swing.JPanel {

    private int[][] matrix;

    /**
     * Creates new form Board
     */
    public Board() {
        int numRows = ConfigData.getInstance().getRows();
        int numCols = ConfigData.getInstance().getCols();
        setLayout(new GridLayout(numRows, numCols));
        initMatrix();
    }

    public void initBoard() {
        int numRows = ConfigData.getInstance().getRows();
        int numCols = ConfigData.getInstance().getCols();
        for (int row = 0; row < numRows; row++) {
            for (int col = 0; col < numCols; col++) {
                MineButton b = new MineButton(row, col);
                add(b);
            }
        }
    }

    public void initMatrix() {
        matrix = new int[ConfigData.getInstance().getRows()][ConfigData.getInstance().getCols()];
        int numRows = ConfigData.getInstance().getRows();
        int numCols = ConfigData.getInstance().getCols();
        for (int row = 0; row < numRows; row++) {
            for (int col = 0; col < numCols; col++) {
                matrix[row][col] = 0;
            }
        }
    }

    public void putBombs() {
        for (int row = 0; row < ConfigData.getInstance().getRows(); row++) {
            for (int col = 0; col < ConfigData.getInstance().getCols(); col++) {
                    matrix[row][col] = -1;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
